dist: xenial

language: java
  
script:
  - gradle clean build
  - tar -zcf hello_world_test_reports.tar.gz build/reports
  - tar -zcf hello_world_executable_distributions.tar.gz build/distributions
  - ls -R

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  - echo "Just generated GIT_TAG"
  - echo $GIT_TAG
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITPERM_RK@github.com/cs3398-s19-klingon-warriors/java-hello-world-with-gradle  --tags
  - ls -R  
deploy:
  provider: releases
  api_key: 
    secure: $GITPERM_RK
    
  file:
  - "README.md"
  - "hello_world_test_reports.tar.gz"
  - "hello_world_executable_distributions.tar.gz"
  
  skip cleanup: true
  
  on:
    tags: false
    branch: r-kelmenson
